### ISSUE TITLE
etypes is not defined

### ISSUE THREAD

**Issue by abarmat** [coinbase/coinbase-node#72] opened 2017-01-19 13:39 UTC
I'm calling the refresh() method from the client using the access_token and refresh_token from a user, I want to refresh and store the new tokens.

I'm getting an HTTP error but the library cannot call the callback as it's expecting an import called etypes that's not there.

    if (err) {
      err.type = etypes.TokenRefreshError;
      callback(err, result);
      return;
    }

**Comment by Kyroy** [comment] 2017-08-24 14:01
The problem is, that it is calling `this._postHttp` which uses
```var url = this.baseApiUri + this._setAccessToken(path);```
and `baseApiUri` is set to `https://api.coinbase.com/v2/`

As a result it is calling:
```
POST https://api.coinbase.com/v2/https://api.coinbase.com/oauth/token?access_token=9b5d1ebb55a4983f5fa26e87a5988b48bea6581324dd90dccd5473d9efb0b63f
404 (Not Found)
```

**Comment by Maximization** [comment] 2017-11-05 21:38
I just pushed a PR that fixes both issues described above

**Comment by drewrothstein** [comment] 2020-01-16 05:32
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed by drewrothstein** 2020-01-16 05:32 UTC
